namespace sprites.builtin {
    //% fixedInstance jres blockIdentity=images._image
    export const bed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const console = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const forestBackground = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestBat7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestFlowers0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestFlowers1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestFlowers2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestLargeMushroom0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestLargeMushroom1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMonkey10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestMushroomPatch = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestScenery0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestScenery1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestScenery2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestScenery3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestSnake7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const forestTiles34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTree0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTree1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTree2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTree3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTreeGroup0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTreeGroup1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTreeGroup2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTreeGroup3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const forestTreeGroup4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureRug = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeShelf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tv = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkRight2 = image.ofBuffer(hex``);
}
